# Generated by Django 2.2.2 on 2019-06-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eid_al_adha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_bakra_info',
            name='text1',
        ),
        migrations.AlterField(
            model_name='add_bakra_info',
            name='text2',
            field=models.TextField(),
        ),
    ]
